version: 2
jobs:
    build:
        working_directory: /go/src/github.com/jobtalk/thor
        docker:
            - image: golang:latest
              environment:
                  GO15VENDOREXPERIMENT: 1
        steps:
            - checkout
            - run:
                name: "Install glide"
                command: |
                    go get github.com/Masterminds/glide
                    go install github.com/Masterminds/glide
            - run:
                name: "Install github-release"
                command: |
                    go get github.com/aktau/github-release
                    go install github.com/aktau/github-release
            - run:
                name: "Install packages"
                command: |
                    glide i
            - run:
                name: "run test"
                command: |
                    go test $(glide novendor)
            - run:
                name: "build thor"
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        make
                    elif [[ "${CIRCLE_BRANCH}" =~ ^release-.* ]]; then
                        VERSION=${CIRCLE_BRANCH#release-} make
                    fi
            - deploy:
                name: "release head version"
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        HASH=$(git rev-parse --short HEAD)
                        github-release release -u jobtalk -r thor -t "${HASH}" -n "${HASH}" -d "${HASH}" -p
                        github-release upload -u jobtalk -r thor -t "${HASH}" --name "thor-darwin-amd64.tar.gz" --file bin/darwin/thor-darwin-amd64.tar.gz
                        github-release upload -u jobtalk -r thor -t "${HASH}" --name "thor-linux-amd64.tar.gz" --file bin/linux/thor-linux-amd64.tar.gz
                    fi
            - deploy:
                name: "release release branch"
                command: |
                    if [[ "$CIRCLE_BRANCH" =~ ^release-.* ]]; then
                        VERSION=${CIRCLE_BRANCH#release-} make
                        VERSION=${CIRCLE_BRANCH#release-}
                        github-release release -u jobtalk -r thor -t "${VERSION}" -n "${VERSION}" -d "${VERSION}" --draft
                        github-release upload -u jobtalk -r thor -t "${VERSION}" --name "thor-darwin-amd64.tar.gz" --file bin/darwin/thor-darwin-amd64.tar.gz
                        github-release upload -u jobtalk -r thor -t "${VERSION}" --name "thor-linux-amd64.tar.gz" --file bin/linux/thor-linux-amd64.tar.gz
                    fi
