version: 2
jobs:
    build:
        working_directory: /go/src/github.com/jobtalk/pnzr
        docker:
            - image: golang:1.10.1
              environment:
                  GO15VENDOREXPERIMENT: 1
        steps:
            - checkout
            - run:
                name: "Install glide"
                command: |
                    go get github.com/Masterminds/glide
                    go install github.com/Masterminds/glide
            - run:
                name: "Install dep"
                command: |
                    go get -u github.com/golang/dep/cmd/dep
            - run:
                name: "check fmt"
                command: |
                    if [ $(go fmt $(glide nv) | wc -l) -eq 0 ]; then
                        exit 0
                    fi
                    echo "Go fmt is not applied."
                    exit 1
            - run:
                name: "Install github-release"
                command: |
                    go get github.com/aktau/github-release
                    go install github.com/aktau/github-release
            - run:
                name: "Install packages"
                command: |
                    dep ensure
            - run:
                name: "run test"
                command: |
                    go test -cover $(glide novendor)
            - run:
                name: "build pnzr"
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        make
                    elif [[ "${CIRCLE_BRANCH}" =~ ^release-.* ]]; then
                        VERSION=${CIRCLE_BRANCH#release-} make
                    fi
            - deploy:
                name: "release release branch"
                command: |
                    if [[ "$CIRCLE_BRANCH" =~ ^release-.* ]]; then
                        VERSION=${CIRCLE_BRANCH#release-} make
                        VERSION=${CIRCLE_BRANCH#release-}
                        github-release release -u jobtalk -r pnzr -t "${VERSION}" -n "${VERSION}" -d "${VERSION}"
                        github-release upload -u jobtalk -r pnzr -t "${VERSION}" --name "pnzr-darwin-amd64" --file bin/darwin/pnzr
                        github-release upload -u jobtalk -r pnzr -t "${VERSION}" --name "pnzr-linux-amd64" --file bin/linux/pnzr
                    fi
